'''
@Author: sakuzeng1213
@Date: 2025-08-20 15:54:01
@LastEditTime: 2025-09-02 15:26:29
@LastEditors: sakuzeng1213
@FilePath: /unitree_sdk2_python_g1/unitree_sdk_python/unitree_sdk2py/idl/unitree_hg/msg/dds_/_LowState_.py
@Description: 
'''
"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_hg.msg.dds_
  IDL file: LowState_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import unitree_hg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowState_(idl.IdlStruct, typename="unitree_hg.msg.dds_.LowState_"):
    version: types.array[types.uint32, 2]
    mode_pr: types.uint8
    mode_machine: types.uint8
    tick: types.uint32
    imu_state: 'unitree_sdk2py.idl.unitree_hg.msg.dds_.IMUState_'
    motor_state: types.array['unitree_sdk2py.idl.unitree_hg.msg.dds_.MotorState_', 35]
    wireless_remote: types.array[types.uint8, 40]
    reserve: types.array[types.uint32, 4]
    crc: types.uint32

"""
version:
类型：types.array[types.uint32, 2]
描述：表示协议或消息的版本号。

mode_pr:
类型：types.uint8
描述：当前的运动模式（如站立、行走等）。

mode_machine:
类型：types.uint8
描述：机器的整体状态模式。
tick:
类型：types.uint32
描述：时间戳或计时器，用于同步或记录状态。

imu_state:
类型：unitree_sdk2py.idl.unitree_hg.msg.dds_.IMUState_
描述：IMU（惯性测量单元）的状态信息。

motor_state:
类型：types.array['unitree_sdk2py.idl.unitree_hg.msg.dds_.MotorState_', 35]
描述：包含 35 个电机的状态信息，每个电机的状态由 MotorState_ 类型定义。

wireless_remote:
类型：types.array[types.uint8, 40]
描述：无线遥控器的状态数据。

reserve:
类型：types.array[types.uint32, 4]
描述：保留字段，用于未来扩展。

crc:
类型：types.uint32
描述：校验码，用于验证数据完整性。
"""
