'''
@Author: sakuzeng1213
@Date: 2025-08-20 15:54:01
@LastEditTime: 2025-09-02 15:51:46
@LastEditors: sakuzeng1213
@FilePath: /unitree_sdk2_python_g1/unitree_sdk_python/unitree_sdk2py/idl/unitree_hg/msg/dds_/_LowCmd_.py
@Description: 
'''
"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: unitree_hg.msg.dds_
  IDL file: LowCmd_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import unitree_hg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowCmd_(idl.IdlStruct, typename="unitree_hg.msg.dds_.LowCmd_"):
    mode_pr: types.uint8
    mode_machine: types.uint8
    motor_cmd: types.array['unitree_sdk2py.idl.unitree_hg.msg.dds_.MotorCmd_', 35]
    reserve: types.array[types.uint32, 4]
    crc: types.uint32
"""
mode_pr:
类型：types.uint8
描述：当前的运动模式（如站立、行走等）。

mode_machine:
类型：types.uint8
描述：机器的整体状态模式。

motor_cmd:
类型：types.array['unitree_sdk2py.idl.unitree_hg.msg.dds_.MotorCmd_', 35]
描述：包含 35 个电机的控制命令，每个电机的命令由 MotorCmd_ 类型定义。

reserve:
类型：types.array[types.uint32, 4]
描述：保留字段，用于未来扩展。

crc:
类型：types.uint32
描述：校验码，用于验证数据完整性。
"""

